### ISSUE TITLE
Step10の7 Kubernetes APIライブラリの利用サンプルでエラーが発生しました。

### ISSUE THREAD

**Issue by OogakiAkiya** [takara9/codes_for_lessons#1]
P262のpythonのコードが上手く動作しなかったため、一度ご確認いただきたいです。

おこなった内容はminikube上で
```
$kubectl apply -f taskQueue-deploy
$docker build --tag job-init:0.1 ./job-initiator.py
$docker run -it --rm --name kube -v `pwd`/py:/py -v ~/.kube:/root/.kube -v ~/.minikube:/Users/[user名]/.minikube job-init:0.1 bash
```

コンテナを起動した後
```
root@ddbfd700e12c:/# cd py

root@ddbfd700e12c:/py# python job-initiator.py
Traceback (most recent call last):
  File "job-initiator.py", line 64, in <module>
    queue = create_queue()
  File "job-initiator.py", line 21, in create_queue
    conn = pika.BlockingConnection(qmgr_pram)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 359, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError
```
以上の内容のエラーが出ております。

**Comment by takara9** [comment]
ポスト先を変更いただき、ありがとうございます。こちらで再現テストして、リプライさせていただきますので、少し時間を頂ければ幸いです。

**Comment by OogakiAkiya** [comment]
お手数ですがよろしくお願い致します。

**Comment by iruca3** [comment]
@OogakiAkiya Hi!
I have the same error when I was re-creating the rabbitmq deployment. I watched rabbitmq's log, but there were no suspicious logs, so I waited 2 or 3 minutes and finally succeeded to connect.
( I also tried to connect with telnet while waiting, it displayed `Connection Refused` but finally connected. )
You might want to try collecting clues by `kubectl logs` and `kubectl describe` for rabbitmq pod.
I hope this helps you.

**Comment by takara9** [comment]
@OogakiAkiya さん、

macOS上のminikubeで確認した結果をお知らせします。

~~~
 maho:~ maho$ brew install minikube
...
maho:~ maho$ minikube start
...
maho:~ maho$ minikube kubectl
...

maho:~ maho$ kubectl get node
NAME       STATUS    ROLES     AGE       VERSION
minikube   Ready     master    60s       v1.18.0
...

maho:~ maho$ kubectl cluster-info
Kubernetes master is running at https://192.168.64.2:8443
KubeDNS is running at https://192.168.64.2:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
~~~

k8sの動作が確認できたところで、minikubeの仮想マシンのIPアドレスを調べます。

~~~
maho:job-initiator maho$ minikube ip
192.168.64.2
~~~

上記の結果から、新しいminikubeのバージョンでは、仮想マシンのIPアドレスが変更になった様です。執筆時のminikubeのバージョンでは、192.168.99.100 でした。

そこで、job-initiator.py  の以下の部分、 qmgr_host のIPアドレスを、これに合わせて変更します。

~~~
# メッセージ・ブローカーと接続
def create_queue():
    qmgr_cred= pika.PlainCredentials('guest', 'guest')
    #qmgr_host='172.16.20.11'  # for vagrant-k8s
    #qmgr_host='192.168.99.100' # for minikube old version
    qmgr_host='192.168.64.2' # for minikube latest version
    qmgr_port='31672'
    qmgr_pram = pika.ConnectionParameters(
    	      host=qmgr_host,
	      port=qmgr_port,
~~~

これで以下の様に動作すると思います。

~~~
maho:job-initiator maho$ docker build --tag job-init:0.1 .
...
maho:job-initiator maho$ docker run -it --name kube -v `pwd`/py:/py -v ~/.kube:/root/.kube -v ~/.minikube:/Users/maho/.minikube job-init:0.1
root@97ac7d7683e3:/# cd py
root@97ac7d7683e3:/py# python job-initiator.py 
...
root@97ac7d7683e3:/py# kubectl get jobs,pod
NAME              COMPLETIONS   DURATION   AGE
job.batch/pngen   4/4           45s        84s

NAME                             READY   STATUS      RESTARTS   AGE
pod/pngen-bfdx9                  0/1     Completed   0          45s
pod/pngen-gwhp8                  0/1     Completed   0          44s
pod/pngen-hcjbh                  0/1     Completed   0          84s
pod/pngen-qs5m5                  0/1     Completed   0          84s
pod/taskqueue-5f6557cd4f-nbwn9   1/1     Running     0          9m29s


root@97ac7d7683e3:/py# kubectl logs pod/pngen-bfdx9 
['1001', ' 2000']
[1009 1013 1019 1021 1031 1033 1039 1049 1051 1061 1063 1069 1087 1091
 1093 1097 1103 1109 1117 1123 1129 1151 1153 1163 1171 1181 1187 1193
~~~

**Comment by takara9** [comment]
Hello, @iruca3 
please see previous post for @OogakiAkiya , I am sorry in Japanese. 
Minikube latest version VM's IP address has been changed.

**Comment by takara9** [comment]
このIssueはクロースします。
